export const RAW = [
  // Arrays / Strings
  {
    n: 3,
    t: "Longest Substring Without Repeating Characters",
    d: "Medium",
    p: "Sliding Window",
    c: "Arrays",
  },
  {
    n: 76,
    t: "Minimum Window Substring",
    d: "Hard",
    p: "Sliding Window",
    c: "Arrays",
  },
  {
    n: 1004,
    t: "Max Consecutive Ones III",
    d: "Medium",
    p: "Sliding Window",
    c: "Arrays",
  },
  {
    n: 904,
    t: "Fruit Into Baskets",
    d: "Medium",
    p: "Sliding Window",
    c: "Arrays",
  },
  {
    n: 424,
    t: "Longest Repeating Character Replacement",
    d: "Medium",
    p: "Sliding Window",
    c: "Arrays",
  },
  {
    n: 167,
    t: "Two Sum II",
    d: "Medium",
    p: "Two Pointers",
    c: "Arrays",
  },
  {
    n: 11,
    t: "Container With Most Water",
    d: "Medium",
    p: "Two Pointers",
    c: "Arrays",
  },
  { n: 15, t: "3Sum", d: "Medium", p: "Two Pointers", c: "Arrays" },
  {
    n: 125,
    t: "Valid Palindrome",
    d: "Easy",
    p: "Two Pointers",
    c: "Arrays",
  },
  {
    n: 42,
    t: "Trapping Rain Water",
    d: "Hard",
    p: "Two Pointers",
    c: "Arrays",
  },
  {
    n: 560,
    t: "Subarray Sum Equals K",
    d: "Medium",
    p: "Prefix Sum",
    c: "Arrays",
  },
  {
    n: 238,
    t: "Product of Array Except Self",
    d: "Medium",
    p: "Prefix Sum",
    c: "Arrays",
  },
  { n: 1, t: "Two Sum", d: "Easy", p: "Hash Map", c: "Arrays" },
  {
    n: 523,
    t: "Continuous Subarray Sum",
    d: "Medium",
    p: "Prefix Sum",
    c: "Arrays",
  },
  {
    n: 142,
    t: "Linked List Cycle II",
    d: "Medium",
    p: "Fast & Slow",
    c: "Linked List",
  },
  {
    n: 287,
    t: "Find the Duplicate Number",
    d: "Medium",
    p: "Fast & Slow",
    c: "Arrays",
  },
  {
    n: 876,
    t: "Middle of the Linked List",
    d: "Easy",
    p: "Fast & Slow",
    c: "Linked List",
  },
  { n: 202, t: "Happy Number", d: "Easy", p: "Fast & Slow", c: "Math" },
  {
    n: 33,
    t: "Search in Rotated Sorted Array",
    d: "Medium",
    p: "Binary Search",
    c: "Arrays",
  },
  {
    n: 153,
    t: "Find Minimum in Rotated Sorted Array",
    d: "Medium",
    p: "Binary Search",
    c: "Arrays",
  },
  {
    n: 875,
    t: "Koko Eating Bananas",
    d: "Medium",
    p: "Binary Search",
    c: "Arrays",
  },
  {
    n: 1011,
    t: "Capacity To Ship Packages Within D Days",
    d: "Medium",
    p: "Binary Search",
    c: "Arrays",
  },
  {
    n: 4,
    t: "Median of Two Sorted Arrays",
    d: "Hard",
    p: "Binary Search",
    c: "Arrays",
  },
  {
    n: 410,
    t: "Split Array Largest Sum",
    d: "Hard",
    p: "BS Answer Space",
    c: "Arrays",
  },
  {
    n: 774,
    t: "Minimize Max Distance to Gas Station",
    d: "Hard",
    p: "BS Answer Space",
    c: "Arrays",
  },
  {
    n: 1552,
    t: "Magnetic Force Between Two Balls",
    d: "Medium",
    p: "BS Answer Space",
    c: "Arrays",
  },
  {
    n: 739,
    t: "Daily Temperatures",
    d: "Medium",
    p: "Monotonic Stack",
    c: "Arrays",
  },
  {
    n: 84,
    t: "Largest Rectangle in Histogram",
    d: "Hard",
    p: "Monotonic Stack",
    c: "Arrays",
  },
  {
    n: 503,
    t: "Next Greater Element II",
    d: "Medium",
    p: "Monotonic Stack",
    c: "Arrays",
  },
  {
    n: 735,
    t: "Asteroid Collision",
    d: "Medium",
    p: "Stack",
    c: "Arrays",
  },
  {
    n: 907,
    t: "Sum of Subarray Minimums",
    d: "Medium",
    p: "Monotonic Stack",
    c: "Arrays",
  },
  {
    n: 56,
    t: "Merge Intervals",
    d: "Medium",
    p: "Intervals",
    c: "Arrays",
  },
  {
    n: 253,
    t: "Meeting Rooms II",
    d: "Medium",
    p: "Intervals",
    c: "Arrays",
  },
  {
    n: 57,
    t: "Insert Interval",
    d: "Medium",
    p: "Intervals",
    c: "Arrays",
  },
  {
    n: 435,
    t: "Non-Overlapping Intervals",
    d: "Medium",
    p: "Intervals",
    c: "Arrays",
  },
  { n: 53, t: "Maximum Subarray", d: "Medium", p: "Kadane", c: "Arrays" },
  {
    n: 918,
    t: "Maximum Sum Circular Subarray",
    d: "Medium",
    p: "Kadane",
    c: "Arrays",
  },
  {
    n: 121,
    t: "Best Time to Buy and Sell Stock",
    d: "Easy",
    p: "Kadane",
    c: "Arrays",
  },
  {
    n: 179,
    t: "Largest Number",
    d: "Medium",
    p: "Sorting Tricks",
    c: "Arrays",
  },
  {
    n: 621,
    t: "Task Scheduler",
    d: "Medium",
    p: "Sorting Tricks",
    c: "Arrays",
  },
  {
    n: 452,
    t: "Minimum Number of Arrows",
    d: "Medium",
    p: "Sorting Tricks",
    c: "Arrays",
  },
  { n: 54, t: "Spiral Matrix", d: "Medium", p: "Matrix", c: "Arrays" },
  { n: 48, t: "Rotate Image", d: "Medium", p: "Matrix", c: "Arrays" },
  {
    n: 73,
    t: "Set Matrix Zeroes",
    d: "Medium",
    p: "Matrix",
    c: "Arrays",
  },
  {
    n: 74,
    t: "Search a 2D Matrix",
    d: "Medium",
    p: "Matrix",
    c: "Arrays",
  },
  {
    n: 49,
    t: "Group Anagrams",
    d: "Medium",
    p: "Frequency Map",
    c: "Arrays",
  },
  {
    n: 242,
    t: "Valid Anagram",
    d: "Easy",
    p: "Frequency Map",
    c: "Arrays",
  },
  {
    n: 169,
    t: "Majority Element",
    d: "Easy",
    p: "Frequency Map",
    c: "Arrays",
  },
  {
    n: 347,
    t: "Top K Frequent Elements",
    d: "Medium",
    p: "Frequency Map",
    c: "Arrays",
  },
  { n: 75, t: "Sort Colors", d: "Medium", p: "Dutch Flag", c: "Arrays" },
  { n: 283, t: "Move Zeroes", d: "Easy", p: "Two Pointers", c: "Arrays" },
  {
    n: 448,
    t: "Find All Numbers Disappeared in Array",
    d: "Easy",
    p: "Cyclic Sort",
    c: "Arrays",
  },
  {
    n: 442,
    t: "Find All Duplicates in Array",
    d: "Medium",
    p: "Cyclic Sort",
    c: "Arrays",
  },
  {
    n: 41,
    t: "First Missing Positive",
    d: "Hard",
    p: "Cyclic Sort",
    c: "Arrays",
  },
  {
    n: 394,
    t: "Decode String",
    d: "Medium",
    p: "String Parsing",
    c: "Strings",
  },
  {
    n: 20,
    t: "Valid Parentheses",
    d: "Easy",
    p: "String Parsing",
    c: "Strings",
  },
  {
    n: 227,
    t: "Basic Calculator II",
    d: "Medium",
    p: "String Parsing",
    c: "Strings",
  },
  {
    n: 71,
    t: "Simplify Path",
    d: "Medium",
    p: "String Parsing",
    c: "Strings",
  },
  {
    n: 206,
    t: "Reverse Linked List",
    d: "Easy",
    p: "LL Reversal",
    c: "Linked List",
  },
  {
    n: 92,
    t: "Reverse Linked List II",
    d: "Medium",
    p: "LL Reversal",
    c: "Linked List",
  },
  {
    n: 25,
    t: "Reverse Nodes in k-Group",
    d: "Hard",
    p: "LL Reversal",
    c: "Linked List",
  },
  {
    n: 24,
    t: "Swap Nodes in Pairs",
    d: "Medium",
    p: "LL Reversal",
    c: "Linked List",
  },
  {
    n: 542,
    t: "01 Matrix",
    d: "Medium",
    p: "Multi-Source BFS",
    c: "Graphs",
  },
  {
    n: 994,
    t: "Rotting Oranges",
    d: "Medium",
    p: "Multi-Source BFS",
    c: "Graphs",
  },
  {
    n: 286,
    t: "Walls and Gates",
    d: "Medium",
    p: "Multi-Source BFS",
    c: "Graphs",
  },
  {
    n: 1926,
    t: "Nearest Exit From Entrance in Maze",
    d: "Medium",
    p: "BFS",
    c: "Graphs",
  },
  {
    n: 215,
    t: "Kth Largest Element in Array",
    d: "Medium",
    p: "QuickSelect",
    c: "Arrays",
  },
  {
    n: 973,
    t: "K Closest Points to Origin",
    d: "Medium",
    p: "QuickSelect",
    c: "Arrays",
  },
  {
    n: 229,
    t: "Majority Element II",
    d: "Medium",
    p: "Boyer-Moore",
    c: "Arrays",
  },
  {
    n: 187,
    t: "Repeated DNA Sequences",
    d: "Medium",
    p: "Rolling Hash",
    c: "Strings",
  },
  {
    n: 1044,
    t: "Longest Duplicate Substring",
    d: "Hard",
    p: "Rolling Hash",
    c: "Strings",
  },
  {
    n: 28,
    t: "Find the Index of the First Occurrence in a String",
    d: "Easy",
    p: "KMP/Z",
    c: "Strings",
  },
  {
    n: 214,
    t: "Shortest Palindrome",
    d: "Hard",
    p: "KMP/Z",
    c: "Strings",
  },
  {
    n: 459,
    t: "Repeated Substring Pattern",
    d: "Easy",
    p: "KMP/Z",
    c: "Strings",
  },
  {
    n: 218,
    t: "The Skyline Problem",
    d: "Hard",
    p: "Line Sweep",
    c: "Strings",
  },
  {
    n: 850,
    t: "Rectangle Area II",
    d: "Hard",
    p: "Line Sweep",
    c: "Arrays",
  },

  // Greedy
  {
    n: 55,
    t: "Jump Game",
    d: "Medium",
    p: "Activity Selection",
    c: "Greedy",
  },
  {
    n: 45,
    t: "Jump Game II",
    d: "Medium",
    p: "Activity Selection",
    c: "Greedy",
  },
  {
    n: 134,
    t: "Gas Station",
    d: "Medium",
    p: "Gas Station",
    c: "Greedy",
  },
  { n: 135, t: "Candy", d: "Hard", p: "Two-Pass Greedy", c: "Greedy" },
  {
    n: 767,
    t: "Reorganize String",
    d: "Medium",
    p: "String Greedy",
    c: "Strings",
  },
  {
    n: 402,
    t: "Remove K Digits",
    d: "Medium",
    p: "String Greedy",
    c: "Strings",
  },
  {
    n: 1167,
    t: "Minimum Cost to Connect Sticks",
    d: "Medium",
    p: "Huffman",
    c: "Strings",
  },

  // Trees
  {
    n: 102,
    t: "Binary Tree Level Order Traversal",
    d: "Medium",
    p: "Tree BFS",
    c: "Trees",
  },
  {
    n: 103,
    t: "Binary Tree Zigzag Level Order Traversal",
    d: "Medium",
    p: "Tree BFS",
    c: "Trees",
  },
  {
    n: 199,
    t: "Binary Tree Right Side View",
    d: "Medium",
    p: "Tree BFS",
    c: "Trees",
  },
  {
    n: 111,
    t: "Minimum Depth of Binary Tree",
    d: "Easy",
    p: "Tree BFS",
    c: "Trees",
  },
  {
    n: 116,
    t: "Populating Next Right Pointers",
    d: "Medium",
    p: "Tree BFS",
    c: "Trees",
  },
  { n: 113, t: "Path Sum II", d: "Medium", p: "Tree DFS", c: "Trees" },
  {
    n: 543,
    t: "Diameter of Binary Tree",
    d: "Easy",
    p: "Tree DFS",
    c: "Trees",
  },
  { n: 101, t: "Symmetric Tree", d: "Easy", p: "Tree DFS", c: "Trees" },
  {
    n: 226,
    t: "Invert Binary Tree",
    d: "Easy",
    p: "Tree DFS",
    c: "Trees",
  },
  {
    n: 124,
    t: "Binary Tree Maximum Path Sum",
    d: "Hard",
    p: "Tree DFS",
    c: "Trees",
  },
  {
    n: 236,
    t: "Lowest Common Ancestor of a Binary Tree",
    d: "Medium",
    p: "LCA",
    c: "Trees",
  },
  {
    n: 235,
    t: "Lowest Common Ancestor of BST",
    d: "Easy",
    p: "LCA",
    c: "Trees",
  },
  {
    n: 230,
    t: "Kth Smallest in BST",
    d: "Medium",
    p: "BST Ops",
    c: "Trees",
  },
  {
    n: 98,
    t: "Validate Binary Search Tree",
    d: "Medium",
    p: "BST Ops",
    c: "Trees",
  },
  { n: 173, t: "BST Iterator", d: "Medium", p: "BST Ops", c: "Trees" },
  {
    n: 450,
    t: "Delete Node in BST",
    d: "Medium",
    p: "BST Ops",
    c: "Trees",
  },
  {
    n: 297,
    t: "Serialize and Deserialize Binary Tree",
    d: "Hard",
    p: "Serialize",
    c: "Trees",
  },
  {
    n: 449,
    t: "Serialize and Deserialize BST",
    d: "Medium",
    p: "Serialize",
    c: "Trees",
  },
  { n: 208, t: "Implement Trie", d: "Medium", p: "Trie", c: "Trees" },
  { n: 212, t: "Word Search II", d: "Hard", p: "Trie", c: "Trees" },
  {
    n: 211,
    t: "Design Add and Search Words",
    d: "Medium",
    p: "Trie",
    c: "Trees",
  },
  { n: 648, t: "Replace Words", d: "Medium", p: "Trie", c: "Trees" },
  {
    n: 307,
    t: "Range Sum Query Mutable",
    d: "Medium",
    p: "Segment Tree",
    c: "Trees",
  },
  {
    n: 315,
    t: "Count of Smaller Numbers After Self",
    d: "Hard",
    p: "Segment Tree",
    c: "Trees",
  },
  {
    n: 105,
    t: "Construct Binary Tree from Preorder and Inorder",
    d: "Medium",
    p: "Tree Construction",
    c: "Trees",
  },
  {
    n: 106,
    t: "Construct Binary Tree from Postorder and Inorder",
    d: "Medium",
    p: "Tree Construction",
    c: "Trees",
  },
  {
    n: 94,
    t: "Binary Tree Inorder Traversal",
    d: "Easy",
    p: "Morris",
    c: "Trees",
  },
  { n: 99, t: "Recover BST", d: "Medium", p: "Morris", c: "Trees" },
  {
    n: 327,
    t: "Count of Range Sum",
    d: "Hard",
    p: "Merge Sort",
    c: "Trees",
  },

  // Graphs
  { n: 127, t: "Word Ladder", d: "Hard", p: "Graph BFS", c: "Graphs" },
  {
    n: 200,
    t: "Number of Islands",
    d: "Medium",
    p: "Graph DFS",
    c: "Graphs",
  },
  {
    n: 547,
    t: "Number Provinces",
    d: "Medium",
    p: "Graph DFS",
    c: "Graphs",
  },
  { n: 733, t: "Flood Fill", d: "Easy", p: "Graph DFS", c: "Graphs" },
  {
    n: 417,
    t: "Pacific Atlantic Water Flow",
    d: "Medium",
    p: "Graph DFS",
    c: "Graphs",
  },
  {
    n: 207,
    t: "Course Schedule",
    d: "Medium",
    p: "Topological Sort",
    c: "Graphs",
  },
  {
    n: 210,
    t: "Course Schedule II",
    d: "Medium",
    p: "Topological Sort",
    c: "Graphs",
  },
  {
    n: 269,
    t: "Alien Dictionary",
    d: "Hard",
    p: "Topological Sort",
    c: "Graphs",
  },
  {
    n: 310,
    t: "Minimum Height Trees",
    d: "Medium",
    p: "Topological Sort",
    c: "Graphs",
  },
  {
    n: 323,
    t: "Number of Connected Components",
    d: "Medium",
    p: "Union-Find",
    c: "Graphs",
  },
  {
    n: 684,
    t: "Redundant Connection",
    d: "Medium",
    p: "Union-Find",
    c: "Graphs",
  },
  {
    n: 721,
    t: "Accounts Merge",
    d: "Medium",
    p: "Union-Find",
    c: "Graphs",
  },
  {
    n: 261,
    t: "Graph Valid Tree",
    d: "Medium",
    p: "Union-Find",
    c: "Graphs",
  },
  {
    n: 743,
    t: "Network Delay Time",
    d: "Medium",
    p: "Dijkstra",
    c: "Graphs",
  },
  {
    n: 787,
    t: "Cheapest Flights Within K Stops",
    d: "Medium",
    p: "Dijkstra",
    c: "Graphs",
  },
  {
    n: 1631,
    t: "Path With Minimum Effort",
    d: "Medium",
    p: "Dijkstra",
    c: "Graphs",
  },
  {
    n: 802,
    t: "Find Eventual Safe States",
    d: "Medium",
    p: "Cycle Detection",
    c: "Graphs",
  },
  {
    n: 785,
    t: "Is Graph Bipartite",
    d: "Medium",
    p: "Bipartite",
    c: "Graphs",
  },
  {
    n: 886,
    t: "Possible Bipartition",
    d: "Medium",
    p: "Bipartite",
    c: "Graphs",
  },
  {
    n: 1334,
    t: "Find the City With the Smallest Number of Neighbors",
    d: "Medium",
    p: "Floyd-Warshall",
    c: "Graphs",
  },
  {
    n: 1584,
    t: "Min Cost to Connect All Points",
    d: "Medium",
    p: "MST",
    c: "Graphs",
  },
  {
    n: 332,
    t: "Reconstruct Itinerary",
    d: "Hard",
    p: "Eulerian",
    c: "Graphs",
  },
  {
    n: 2097,
    t: "Valid Arrangement of Pairs",
    d: "Hard",
    p: "Eulerian",
    c: "Graphs",
  },
  {
    n: 1192,
    t: "Critical Connections in a Network",
    d: "Hard",
    p: "SCC",
    c: "Graphs",
  },

  // Design
  { n: 146, t: "LRU Cache", d: "Medium", p: "LRU Cache", c: "Design" },
  { n: 460, t: "LFU Cache", d: "Hard", p: "LRU Cache", c: "Design" },
  {
    n: 692,
    t: "Top K Frequent Words",
    d: "Medium",
    p: "Top-K Heap",
    c: "Heap",
  },
  {
    n: 23,
    t: "Merge K Sorted Lists",
    d: "Hard",
    p: "Top-K Heap",
    c: "Heap",
  },
  {
    n: 295,
    t: "Find Median From Data Stream",
    d: "Hard",
    p: "Two-Heap Median",
    c: "Heap",
  },
  {
    n: 480,
    t: "Sliding Window Median",
    d: "Hard",
    p: "Two-Heap Median",
    c: "Heap",
  },
  {
    n: 239,
    t: "Sliding Window Maximum",
    d: "Hard",
    p: "Sliding Window Max",
    c: "Design",
  },
  {
    n: 1696,
    t: "Jump Game VI",
    d: "Medium",
    p: "Sliding Window Max",
    c: "Design",
  },
  { n: 155, t: "Min Stack", d: "Easy", p: "Stack Design", c: "Design" },
  {
    n: 150,
    t: "Evaluate Reverse Polish Notation",
    d: "Medium",
    p: "Stack Design",
    c: "Design",
  },
  {
    n: 224,
    t: "Basic Calculator",
    d: "Hard",
    p: "Stack Design",
    c: "Design",
  },
  {
    n: 341,
    t: "Flatten Nested List Iterator",
    d: "Medium",
    p: "Iterator Design",
    c: "Design",
  },
  {
    n: 284,
    t: "Peeking Iterator",
    d: "Medium",
    p: "Iterator Design",
    c: "Design",
  },
  {
    n: 355,
    t: "Design Twitter",
    d: "Medium",
    p: "Heap + Design",
    c: "Heap",
  },
  {
    n: 1268,
    t: "Search Suggestions System",
    d: "Medium",
    p: "Trie Design",
    c: "Heap",
  },
  {
    n: 677,
    t: "Map Sum Pairs",
    d: "Medium",
    p: "Trie Design",
    c: "Design",
  },
  {
    n: 1206,
    t: "Design Skiplist",
    d: "Hard",
    p: "Skip List",
    c: "Design",
  },
  {
    n: 382,
    t: "Linked List Random Node",
    d: "Medium",
    p: "Reservoir",
    c: "Design",
  },
  {
    n: 528,
    t: "Random Pick With Weight",
    d: "Medium",
    p: "Prefix Sum + BS",
    c: "Design",
  },

  // Dynamic Programming
  { n: 70, t: "Climbing Stairs", d: "Easy", p: "1D DP", c: "DP" },
  { n: 198, t: "House Robber", d: "Medium", p: "1D DP", c: "DP" },
  { n: 91, t: "Decode Ways", d: "Medium", p: "1D DP", c: "DP" },
  {
    n: 746,
    t: "Min Cost Climbing Stairs",
    d: "Easy",
    p: "1D DP",
    c: "DP",
  },
  { n: 322, t: "Coin Change", d: "Medium", p: "Knapsack", c: "DP" },
  {
    n: 416,
    t: "Partition Equal Subset Sum",
    d: "Medium",
    p: "Knapsack", c: "DP",
  },
  { n: 494, t: "Target Sum", d: "Medium", p: "Knapsack", c: "DP" },
  {
    n: 1049,
    t: "Last Stone Weight II",
    d: "Medium",
    p: "Knapsack",
    c: "DP",
  },
  {
    n: 1143,
    t: "Longest Common Subsequence",
    d: "Medium",
    p: "LCS",
    c: "DP",
  },
  { n: 72, t: "Edit Distance", d: "Hard", p: "LCS", c: "DP" },
  { n: 115, t: "Distinct Subsequences", d: "Hard", p: "LCS", c: "DP" },
  {
    n: 1092,
    t: "Shortest Common Supersequence",
    d: "Hard",
    p: "LCS",
    c: "DP",
  },
  {
    n: 300,
    t: "Longest Increasing Subsequence",
    d: "Medium",
    p: "LIS",
    c: "DP",
  },
  { n: 354, t: "Russian Doll Envelopes", d: "Hard", p: "LIS", c: "DP" },
  { n: 673, t: "Number of LIS", d: "Medium", p: "LIS", c: "DP" },
  {
    n: 5,
    t: "Longest Palindromic Substring",
    d: "Medium",
    p: "Palindrome DP",
    c: "DP",
  },
  {
    n: 647,
    t: "Palindromic Substrings",
    d: "Medium",
    p: "Palindrome DP",
    c: "DP",
  },
  {
    n: 516,
    t: "Longest Palindromic Subsequence",
    d: "Medium",
    p: "Palindrome DP",
    c: "DP",
  },
  {
    n: 132,
    t: "Palindrome Partitioning II",
    d: "Hard",
    p: "Palindrome DP",
    c: "DP",
  },
  { n: 139, t: "Word Break", d: "Medium", p: "Word Break", c: "DP" },
  { n: 140, t: "Word Break II", d: "Hard", p: "Word Break", c: "DP" },
  {
    n: 472,
    t: "Concatenated Words",
    d: "Hard",
    p: "Word Break",
    c: "DP",
  },
  { n: 312, t: "Burst Balloons", d: "Hard", p: "Interval DP", c: "DP" },
  {
    n: 1130,
    t: "Minimum Cost Tree From Leaf Values",
    d: "Medium",
    p: "Interval DP",
    c: "DP",
  },
  { n: 337, t: "House Robber III", d: "Medium", p: "Tree DP", c: "DP" },
  {
    n: 698,
    t: "Partition to K Equal Sum Subsets",
    d: "Medium",
    p: "Bitmask DP",
    c: "DP",
  },
  { n: 78, t: "Subsets", d: "Medium", p: "Backtracking", c: "DP" },
  { n: 46, t: "Permutations", d: "Medium", p: "Backtracking", c: "DP" },
  {
    n: 39,
    t: "Combination Sum",
    d: "Medium",
    p: "Backtracking",
    c: "DP",
  },
  { n: 51, t: "N-Queens", d: "Hard", p: "Backtracking", c: "DP" },
  { n: 37, t: "Sudoku Solver", d: "Hard", p: "Backtracking", c: "DP" },
  {
    n: 131,
    t: "Palindrome Partitioning",
    d: "Medium",
    p: "Backtracking",
    c: "DP",
  },
  {
    n: 62,
    t: "Unique Paths",
    d: "Medium",
    p: "Memoized Recursion",
    c: "DP",
  },
  {
    n: 931,
    t: "Minimum Falling Path Sum",
    d: "Medium",
    p: "Memoized Recursion",
    c: "DP",
  },
  {
    n: 1463,
    t: "Cherry Pickup II",
    d: "Hard",
    p: "Memoized Recursion",
    c: "DP",
  },
  {
    n: 357,
    t: "Count Numbers With Unique Digits",
    d: "Medium",
    p: "Digit DP",
    c: "DP",
  },
  {
    n: 123,
    t: "Best Time to Buy and Sell Stock III",
    d: "Hard",
    p: "Stock DP",
    c: "DP",
  },
  {
    n: 309,
    t: "Best Time With Cooldown",
    d: "Medium",
    p: "Stock DP",
    c: "DP",
  },
  {
    n: 714,
    t: "Best Time With Fee",
    d: "Medium",
    p: "Stock DP",
    c: "DP",
  },
  {
    n: 241,
    t: "Different Ways to Add Parentheses",
    d: "Medium",
    p: "Divide & Conquer",
    c: "DP",
  },
  {
    n: 282,
    t: "Expression Add Operators",
    d: "Hard",
    p: "Backtracking",
    c: "DP",
  },
  { n: 454, t: "4Sum II", d: "Medium", p: "Meet in Middle", c: "DP" },
  {
    n: 1425,
    t: "Constrained Subsequence Sum",
    d: "Hard",
    p: "Deque DP",
    c: "DP",
  },

  // Math / Bits
  {
    n: 136,
    t: "Single Number",
    d: "Easy",
    p: "Bit Manipulation",
    c: "Math",
  },
  {
    n: 191,
    t: "Number of 1 Bits",
    d: "Easy",
    p: "Bit Manipulation",
    c: "Math",
  },
  {
    n: 190,
    t: "Reverse Bits",
    d: "Easy",
    p: "Bit Manipulation",
    c: "Math",
  },
  {
    n: 268,
    t: "Missing Number",
    d: "Easy",
    p: "Bit Manipulation",
    c: "Math",
  },
  { n: 204, t: "Count Primes", d: "Medium", p: "Math Tricks", c: "Math" },
  {
    n: 264,
    t: "Ugly Number II",
    d: "Medium",
    p: "Math Tricks",
    c: "Math",
  },
  {
    n: 1071,
    t: "GCD of Strings",
    d: "Easy",
    p: "Math Tricks",
    c: "Math",
  },
  {
    n: 384,
    t: "Shuffle an Array",
    d: "Medium",
    p: "Randomization",
    c: "Math",
  },
  {
    n: 470,
    t: "Implement Rand7 Using Rand5",
    d: "Medium",
    p: "Randomization",
    c: "Math",
  },
  {
    n: 149,
    t: "Max Points on a Line",
    d: "Hard",
    p: "Geometry",
    c: "Math",
  },
  {
    n: 118,
    t: "Pascal's Triangle",
    d: "Easy",
    p: "Combinatorics",
    c: "Math",
  },
];

export const LEGENDARY = new Set([
  1, 3, 11, 15, 20, 21, 42, 49, 53, 56, 70, 73, 76, 98, 102, 103, 121,
  125, 127, 128, 138, 139, 141, 146, 150, 153, 155, 167, 169, 189, 198,
  199, 200, 206, 207, 210, 215, 217, 219, 226, 235, 236, 238, 239, 242,
  253, 261, 269, 283, 295, 297, 322, 332, 344, 347, 394, 415, 424, 438,
  448, 449, 460, 494, 547, 560, 567, 621, 647, 692, 704, 733, 739, 743,
  746, 752, 767, 787, 875, 876, 907, 973, 994, 1004, 1011, 1143, 1268,
  1631, 1971,
]);

export const PROBLEMS = RAW.map((r, i) => ({
  id: i,
  n: r.n,
  t: r.t,
  d: r.d,
  p: r.p,
  c: r.c,
  starred: LEGENDARY.has(r.n),
}));

export const DIFF_CLASS = {
  Easy: "diff-easy",
  Medium: "diff-med",
  Hard: "diff-hard",
};

export const SLUG_MAP = {
const SLUG_MAP = {
  1: "two-sum",
  3: "longest-substring-without-repeating-characters",
  4: "median-of-two-sorted-arrays",
  5: "longest-palindromic-substring",
  11: "container-with-most-water",
  15: "3sum",
  20: "valid-parentheses",
  23: "merge-k-sorted-lists",
  24: "swap-nodes-in-pairs",
  25: "reverse-nodes-in-k-group",
  28: "find-the-index-of-the-first-occurrence-in-a-string",
  33: "search-in-rotated-sorted-array",
  37: "sudoku-solver",
  39: "combination-sum",
  41: "first-missing-positive",
  42: "trapping-rain-water",
  45: "jump-game-ii",
  46: "permutations",
  48: "rotate-image",
  49: "group-anagrams",
  51: "n-queens",
  53: "maximum-subarray",
  54: "spiral-matrix",
  55: "jump-game",
  56: "merge-intervals",
  57: "insert-interval",
  62: "unique-paths",
  70: "climbing-stairs",
  71: "simplify-path",
  72: "edit-distance",
  73: "set-matrix-zeroes",
  74: "search-a-2d-matrix",
  75: "sort-colors",
  76: "minimum-window-substring",
  78: "subsets",
  84: "largest-rectangle-in-histogram",
  91: "decode-ways",
  92: "reverse-linked-list-ii",
  94: "binary-tree-inorder-traversal",
  98: "validate-binary-search-tree",
  99: "recover-binary-search-tree",
  101: "symmetric-tree",
  102: "binary-tree-level-order-traversal",
  103: "binary-tree-zigzag-level-order-traversal",
  105: "construct-binary-tree-from-preorder-and-inorder-traversal",
  106: "construct-binary-tree-from-inorder-and-postorder-traversal",
  111: "minimum-depth-of-binary-tree",
  113: "path-sum-ii",
  115: "distinct-subsequences",
  116: "populating-next-right-pointers-in-each-node",
  118: "pascals-triangle",
  121: "best-time-to-buy-and-sell-stock",
  123: "best-time-to-buy-and-sell-stock-iii",
  124: "binary-tree-maximum-path-sum",
  125: "valid-palindrome",
  127: "word-ladder",
  131: "palindrome-partitioning",
  132: "palindrome-partitioning-ii",
  134: "gas-station",
  135: "candy",
  136: "single-number",
  139: "word-break",
  140: "word-break-ii",
  142: "linked-list-cycle-ii",
  146: "lru-cache",
  149: "max-points-on-a-line",
  150: "evaluate-reverse-polish-notation",
  153: "find-minimum-in-rotated-sorted-array",
  155: "min-stack",
  167: "two-sum-ii-input-array-is-sorted",
  169: "majority-element",
  173: "binary-search-tree-iterator",
  179: "largest-number",
  187: "repeated-dna-sequences",
  190: "reverse-bits",
  191: "number-of-1-bits",
  198: "house-robber",
  199: "binary-tree-right-side-view",
  200: "number-of-islands",
  202: "happy-number",
  204: "count-primes",
  206: "reverse-linked-list",
  207: "course-schedule",
  208: "implement-trie-prefix-tree",
  210: "course-schedule-ii",
  211: "design-add-and-search-words-data-structure",
  212: "word-search-ii",
  214: "shortest-palindrome",
  215: "kth-largest-element-in-an-array",
  218: "the-skyline-problem",
  224: "basic-calculator",
  226: "invert-binary-tree",
  227: "basic-calculator-ii",
  229: "majority-element-ii",
  230: "kth-smallest-element-in-a-bst",
  235: "lowest-common-ancestor-of-a-binary-search-tree",
  236: "lowest-common-ancestor-of-a-binary-tree",
  238: "product-of-array-except-self",
  239: "sliding-window-maximum",
  241: "different-ways-to-add-parentheses",
  242: "valid-anagram",
  253: "meeting-rooms-ii",
  261: "graph-valid-tree",
  264: "ugly-number-ii",
  268: "missing-number",
  269: "alien-dictionary",
  282: "expression-add-operators",
  283: "move-zeroes",
  284: "peeking-iterator",
  286: "walls-and-gates",
  287: "find-the-duplicate-number",
  295: "find-median-from-data-stream",
  297: "serialize-and-deserialize-binary-tree",
  300: "longest-increasing-subsequence",
  307: "range-sum-query-mutable",
  309: "best-time-to-buy-and-sell-stock-with-cooldown",
  310: "minimum-height-trees",
  312: "burst-balloons",
  315: "count-of-smaller-numbers-after-self",
  322: "coin-change",
  323: "number-of-connected-components-in-an-undirected-graph",
  327: "count-of-range-sum",
  332: "reconstruct-itinerary",
  337: "house-robber-iii",
  341: "flatten-nested-list-iterator",
  347: "top-k-frequent-elements",
  354: "russian-doll-envelopes",
  355: "design-twitter",
  357: "count-numbers-with-unique-digits",
  382: "linked-list-random-node",
  384: "shuffle-an-array",
  394: "decode-string",
  402: "remove-k-digits",
  410: "split-array-largest-sum",
  416: "partition-equal-subset-sum",
  417: "pacific-atlantic-water-flow",
  424: "longest-repeating-character-replacement",
  435: "non-overlapping-intervals",
  442: "find-all-duplicates-in-an-array",
  448: "find-all-numbers-disappeared-in-an-array",
  449: "serialize-and-deserialize-bst",
  450: "delete-node-in-a-bst",
  452: "minimum-number-of-arrows-to-burst-balloons",
  454: "4sum-ii",
  459: "repeated-substring-pattern",
  460: "lfu-cache",
  470: "implement-rand10-using-rand7",
  472: "concatenated-words",
  480: "sliding-window-median",
  494: "target-sum",
  503: "next-greater-element-ii",
  516: "longest-palindromic-subsequence",
  523: "continuous-subarray-sum",
  528: "random-pick-with-weight",
  542: "01-matrix",
  543: "diameter-of-binary-tree",
  547: "number-of-provinces",
  560: "subarray-sum-equals-k",
  621: "task-scheduler",
  647: "palindromic-substrings",
  648: "replace-words",
  673: "number-of-longest-increasing-subsequence",
  677: "map-sum-pairs",
  684: "redundant-connection",
  692: "top-k-frequent-words",
  698: "partition-to-k-equal-sum-subsets",
  714: "best-time-to-buy-and-sell-stock-with-transaction-fee",
  721: "accounts-merge",
  733: "flood-fill",
  735: "asteroid-collision",
  739: "daily-temperatures",
  743: "network-delay-time",
  746: "min-cost-climbing-stairs",
  767: "reorganize-string",
  774: "minimize-max-distance-to-gas-station",
  785: "is-graph-bipartite",
  787: "cheapest-flights-within-k-stops",
  802: "find-eventual-safe-states",
  850: "rectangle-area-ii",
  875: "koko-eating-bananas",
  876: "middle-of-the-linked-list",
  886: "possible-bipartition",
  904: "fruit-into-baskets",
  907: "sum-of-subarray-minimums",
  918: "maximum-sum-circular-subarray",
  931: "minimum-falling-path-sum",
  973: "k-closest-points-to-origin",
  994: "rotting-oranges",
  1004: "max-consecutive-ones-iii",
  1011: "capacity-to-ship-packages-within-d-days",
  1044: "longest-duplicate-substring",
  1049: "last-stone-weight-ii",
  1071: "greatest-common-divisor-of-strings",
  1092: "shortest-common-supersequence",
  1130: "minimum-cost-tree-from-leaf-values",
  1143: "longest-common-subsequence",
  1167: "minimum-cost-to-connect-sticks",
  1192: "critical-connections-in-a-network",
  1206: "design-skiplist",
  1268: "search-suggestions-system",
  1334: "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance",
  1425: "constrained-subsequence-sum",
  1463: "cherry-pickup-ii",
  1552: "magnetic-force-between-two-balls",
  1584: "min-cost-to-connect-all-points",
  1631: "path-with-minimum-effort",
  1696: "jump-game-vi",
  1926: "nearest-exit-from-entrance-in-maze",
  2097: "valid-arrangement-of-pairs",
};

export function lcUrl(p) {
  return `https://leetcode.com/problems/${SLUG_MAP[p.n]}/`;
}
